CREATE  TABLE "public".proton_normalized (
  streak_charge_uuid   uuid  NOT NULL ,
  revenue_model        text   ,
 	secondary_revenue_model text   ,
 	customer_acquisition_channel text   ,
 	secondary_customer_acquisition_channel text   ,
	user_revenue         text   ,
	product_stage        text   ,
  industry             text,
  tam_value            float  NOT NULL ,
	tam_scenario         text  NOT NULL ,
	tam_currency         char(3)  NOT NULL ,
	tam_date             date  NOT NULL ,
	tam_date_precision   text  NOT NULL ,
	tam_geography        text   ,
	tam_source           text   ,
	tam_source_date      text   ,
	tam_past_growth_rate_yearly integer   ,
	tam_future_growth_rate_yearly integer   ,
  sam_uuid             uuid  NOT NULL ,
	sam_value            float  NOT NULL ,
	sam_scenario         text  NOT NULL ,
	sam_currency         char(3)  NOT NULL ,
	sam_date             date  NOT NULL ,
	sam_date_precision   text  NOT NULL ,
	sam_geography        text   ,
	sam_source           text   ,
	sam_source_date      text   ,
	sam_past_growth_rate_yearly integer   ,
	sam_future_growth_rate_yearly integer   ,
	som_value            float  NOT NULL ,
	som_scenario         text  NOT NULL ,
	som_currency         char(3)  NOT NULL ,
	som_date             date  NOT NULL ,
	som_date_precision   text  NOT NULL ,
	som_geography        text   ,
	som_source           text   ,
	som_source_date      text   ,
	som_past_growth_rate_yearly integer   ,
	som_future_growth_rate_yearly integer   ,
	f_revenue_value      float  NOT NULL ,
	f_revenue_currency   char(3)  NOT NULL ,
	f_revenue_date       date  NOT NULL ,
	f_revenue_date_precision text  NOT NULL ,
	f_revenue_period     text  NOT NULL ,
	market_size_slide    boolean  NOT NULL ,
	team_slide           boolean  NOT NULL ,
	why_now_slide        boolean  NOT NULL ,
	problem_slide        boolean  NOT NULL ,
	solution_slide       boolean  NOT NULL ,
	company_purpose_slide boolean  NOT NULL ,
	traction_slide       boolean  NOT NULL ,
	competition_slide    boolean  NOT NULL ,
	business_model_slide boolean  NOT NULL ,
	financials_slide     boolean  NOT NULL ,
	fundraising_ask_slide boolean  NOT NULL ,
	gtm_slide            boolean  NOT NULL ,
	product_slide        boolean  NOT NULL ,
	pre_m_valuation      float  NOT NULL ,
	pre_m_scenario       text  NOT NULL ,
	pre_m_currency       char(3)  NOT NULL ,
	pre_m_date           date  NOT NULL ,
	pre_m_date_precision text  NOT NULL ,
	ask_value            float  NOT NULL ,
	ask_currency         char(3)  NOT NULL ,
	ask_date             date  NOT NULL ,
	ask_date_precision   text  NOT NULL ,
	ask_lower_bound      float   ,
	ask_upper_bound      float   ,
	ask_already_committed float   ,
	h_revenue_value      float  NOT NULL ,
	h_revenue_currency   char(3)  NOT NULL ,
	h_revenue_date       date  NOT NULL ,
	h_revenue_date_precision text  NOT NULL ,
	h_revenue_period     text  NOT NULL ,
	ltv_value            float  NOT NULL ,
	ltv_scenario         text  NOT NULL ,
	ltv_currency         char(3)  NOT NULL ,
	ltv_date             date  NOT NULL ,
	ltv_date_precision   text  NOT NULL ,
	ltv_expected_relationship_years float ,
  gross_margin_value   float  NOT NULL ,
	gross_margin_scenario text  NOT NULL ,
	gross_margin_currency char(3)  NOT NULL ,
	gross_margin_date    date  NOT NULL ,
	gross_margin_date_precision text  NOT NULL ,
	gross_margin_period  text  NOT NULL ,
	cac_value            float  NOT NULL ,
	cac_scenario         text  NOT NULL ,
	cac_currency         char(3)  NOT NULL ,
	cac_date             date  NOT NULL ,
	cac_date_precision   text  NOT NULL ,
	monthly_burn_rate_value float  NOT NULL ,
	burn_rate_scenario   text  NOT NULL ,
	burn_rate_currency   char(3)  NOT NULL ,
	burn_rate_runway_months smallint  NOT NULL ,
	aov_value            float  NOT NULL ,
	aov_scenario         text  NOT NULL ,
	aov_currency         char(3)  NOT NULL ,
	aov_date             date  NOT NULL ,
	aov_date_precision   text  NOT NULL 
 );
